[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_SUPABASE_URL = "https://rpodcxdsljvuysjixztd.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwb2RjeGRzbGp2dXlzaWp4enRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTEwNjEsImV4cCI6MjA2OTU2NzA2MX0.vQBJTl-UctTEtjEXuFikXqwF3wWjJlz8g-LzcBSNeOE"